/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OxRiTCSDfZl
 */
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import Link from "next/link"

export function Tablero() {
  return (
    <div className="grid w-full overflow-hidden lg:grid-cols-[1fr_2fr]">
      <aside className="hidden overflow-auto border-r bg-zinc-100/40 lg:block dark:bg-zinc-800/40">
        <div className="flex flex-col gap-2 p-4">
          <h2 className="text-lg font-semibold">Orders</h2>
          <div className="p-2 border rounded-lg shadow-sm">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Order ID</TableHead>
                  <TableHead>Type</TableHead>
                  <TableHead className="text-right">Budget</TableHead>
                  <TableHead>Date</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell className="font-medium">#3201</TableCell>
                  <TableCell>Rent</TableCell>
                  <TableCell className="text-right">$1,500</TableCell>
                  <TableCell>June 23, 2023</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">#3202</TableCell>
                  <TableCell>Sell</TableCell>
                  <TableCell className="text-right">$300,000</TableCell>
                  <TableCell>June 20, 2023</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
        </div>
      </aside>
      <main className="flex flex-col p-4 overflow-auto md:gap-8 md:p-6">
        <h1 className="text-lg font-semibold md:text-xl">Order Details</h1>
        <Card>
          <CardHeader>
            <CardTitle>Order Data</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-2 md:grid-cols-2">
              <div>Type: Rent</div>
              <div>Operation: Long Term</div>
              <div>Budget: $1,500</div>
              <div>Area: Downtown</div>
              <div>Characteristics: 2 Bedrooms, 1 Bathroom, Furnished</div>
              <div>Contact: John Doe</div>
              <div>Date: June 23, 2023</div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Properties</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="p-2 border rounded-lg shadow-sm">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Type</TableHead>
                    <TableHead>Area</TableHead>
                    <TableHead className="text-right">Price</TableHead>
                    <TableHead>Bedrooms</TableHead>
                    <TableHead>URL</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>Apartment</TableCell>
                    <TableCell>Downtown</TableCell>
                    <TableCell className="text-right">$1,500</TableCell>
                    <TableCell>2</TableCell>
                    <TableCell>
                      <Link className="text-blue-500 underline" href="#">
                        View Property
                      </Link>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>Studio</TableCell>
                    <TableCell>Suburbs</TableCell>
                    <TableCell className="text-right">$1,200</TableCell>
                    <TableCell>1</TableCell>
                    <TableCell>
                      <Link className="text-blue-500 underline" href="#">
                        View Property
                      </Link>
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </div>
          </CardContent>
        </Card>
      </main>
    </div>
  )
}
